export const SAVED_QUESTION_LIST = 'SAVED_QUESTION_LIST'
export const SAVED_CURRENT_QUESTION = 'SAVED_CURRENT_QUESTION'
export const SAVED_ANSWERS = 'SAVED_ANSWERS'
export const SAVED_TYPE = 'SAVED_TYPE'